### PR TITLE
Add zh_cn.json

### PR DESCRIPTION
**Pull request by ThearchyHelios**

### CODE REVIEW

**Comment by DenisD3D** [comment]
Hi,
Thanks for this awesome PR !
I'm waiting a bit before merging it because I'm working on a big update that will require a few changes to the lang file

**Comment by DenisD3D** [comment]
Hey,
Soory for the delay
I finished the first beta for 4.0.0
I tried to made the config file more clear in this version so i rewrote a part of the comments : https://github.com/DenisD3D/Mc2Discord/blob/main/mc2discord-core/src/main/resources/assets/mc2discord/m2d-lang/core/en_us.json
To make lang file more maintable, I'm thinking of translating only values and not comment so it's easier for me to keep them up-to-date with new versions (that means translation only keys ending with .value). What do you think ?
If a key is missing in a lang file, it fallback to english so just removing the .comment keys should work
Thanks
Denis

**Comment by ThearchyHelios** [comment]
HEY Denis!
I'm so glad to hear you that you successfully completed version 4.0! Congrats!
If I understand you correctly, I only need to translate the key at the end of `.value` and leave the key of `.comment` alone right?

**Comment by DenisD3D** [comment]
Yeah, like that i can keep myself translation somewhat uptodate after a contribution
Sorry for the part you already translated ;(

**Comment by ThearchyHelios** [comment]
Hahahaha that's not a problem! Glad i can help with your project!

**Pull request closed without merging**
